# Generated by Django 3.2.7 on 2023-04-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0007_auto_20230403_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='closing_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='closing_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
