# Generated by Django 3.2.7 on 2023-04-05 00:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstone_app', '0008_auto_20230404_0152'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('author', 'stocks')},
        ),
    ]
