# Generated by Django 3.2.7 on 2023-04-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0012_alter_portfolio_stocks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together=set(),
        ),
    ]
