# Generated by Django 3.2.7 on 2023-04-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0013_alter_portfolio_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lists', models.JSONField(default=dict)),
            ],
        ),
    ]
