# Generated by Django 3.2.7 on 2023-04-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0014_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_data', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
