# Generated by Django 3.2.7 on 2023-04-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolios',
            name='emai',
        ),
    ]
