# Generated by Django 3.2.7 on 2023-04-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0002_remove_portfolios_emai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='closing_price',
            field=models.FloatField(),
        ),
    ]
