# Generated by Django 3.2.7 on 2023-04-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0003_alter_portfolios_closing_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='stock_name',
        ),
    ]
