# Generated by Django 3.2.7 on 2023-04-03 18:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstone_app', '0004_auto_20230403_1807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolios',
            new_name='Portfolio',
        ),
        migrations.RenameModel(
            old_name='Stocks',
            new_name='Stock',
        ),
    ]
