# Generated by Django 3.2.7 on 2023-04-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0005_auto_20230403_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='stocks',
            field=models.ManyToManyField(to='capstone_app.Stock'),
        ),
    ]
