# Generated by Django 3.2.7 on 2023-04-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0007_auto_20230403_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='stocks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone_app.stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
