# Generated by Django 3.2.7 on 2023-04-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0008_auto_20230403_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(max_length=100),
        ),
    ]
